version: "3"
services:
  hub:
    image: selenium/hub:4.1.4
  chrome:
    image: selenium/node-chrome:4.1.4
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
  firefox:
    image: selenium/node-firefox:4.1.4
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
  search-module:
    image: anupshaha/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=searchModule.xml
    volumes:
      - ./output/search-result:/user/share/udemy/test-output
  book-flight-module:
    image: anupshaha/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=bookFlightModule.xml
    volumes:
      - ./output/bookFlight-result:/user/share/udemy/test-output